#cloud-config

package_update: true

packages:
  - ufw
  - docker.io
  - docker-compose

runcmd:
  # Enable the firewall
  - ufw enable
  # Allow OpenSSH
  - ufw allow OpenSSH
  # Ensure Docker service starts automatically
  - systemctl start docker
  - systemctl enable docker
  # Clone the repository
  - ['git', 'clone', 'https://github.com/fone-almosca/essentials-services.git', '/root/essentials-services']
  # Navigate to the directory and run Docker Compose
  - ['docker-compose', '-f', '/root/essentials-services/essential-services.yaml', 'up', '-d']
