#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
  - ufw
  - nginx

runcmd:
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw enable
  # enable fail2ban
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  # Ensure Docker service starts automatically
  - systemctl start docker
  - systemctl enable docker
  # Clone the repository
  - ['git', 'clone', 'https://github.com/fone-almosca/essentials-services.git', '/home/essentials-services']
  # Navigate to the directory and run Docker Compose
  - ['docker', 'compose', '-f', '/home/essentials-services/essential-services.yml', 'up', '-d']
  - reboot
