#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
  - ufw
  - nginx
  - git
  - fail2ban
  - unattended-upgrades
  - ntp

write_files:
  # Configure Docker log limits
  - path: /etc/docker/daemon.json
    permissions: '0644'
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "1m",
          "max-file": "1"
        }
      }

  # Fail2Ban SSH protection
  - path: /etc/fail2ban/jail.local
    permissions: '0644'
    content: |
      [sshd]
      enabled = true
      banaction = iptables-multiport
      maxretry = 5
      bantime = 600
      findtime = 600

runcmd:

  # Enable UFW firewall rules
  - ufw allow OpenSSH
  - ufw allow 'Nginx Full'
  - ufw --force enable

  # Enable automatic security updates
  - dpkg-reconfigure -f noninteractive unattended-upgrades

  # Ensure Fail2Ban starts at boot
  - systemctl enable fail2ban
  - systemctl start fail2ban

  # Ensure Docker service starts automatically
  - systemctl enable docker
  - systemctl start docker

  # Apply new Docker log config
  - systemctl restart docker

  # Ensure the directory exists
  - mkdir -p /home/essentials-services

  # Clone
  - ['git', 'clone', 'https://github.com/fone-almosca/essentials-services.git', '/home/essentials-services']	
  # Deploy essential services
  - ['docker','compose', '-f', '/home/essentials-services/essential-services.yml', 'up', '-d']
  - reboot
